name: Hackage

on:
  release:
    types:
      - published

jobs:
  hackage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: sdist
        run: |
          set -ex
          autoreconf -i
          mkdir sdist-out
          cabal sdist -o sdist-out

      - name: upload
        run: |
          set -ex
          curl \
            --silent --show-error --fail \
            --header "Accept: text/plain" \
            --header "Authorization: X-ApiKey ${{ secrets.HACKAGE_API_KEY }}" \
            --form "package=@sdist-out/${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.tar.gz" \
            https://hackage.haskell.org/packages/candidates/
